name: Generate Documentation

on:
  release:
    types: [published]
    
jobs:
  # Split the generation of the sourcekitten json across 9 jobs to speed up the process.
  # At the end of each job the results are uploaded as an artifact. This is required because
  # if the process is done in one job it takes over an hour to generate the help files
  # and the GITHUB_TOKEN expires and it is not possible to commit the changes.
  build-json:
    name: Build sourcekitten json
    runs-on: macOS-latest
    strategy:
      matrix:
        chunk: [0,1,2,3,4,5,6,7,8]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install
        run: brew install sourcekitten
      - name: Build
        run: ./scripts/build-json-doc.sh ${{ matrix.chunk }} 9
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: sourcekitten-${{ matrix.chunk }}
          path: ./sourcekitten/

  # This job requires the previous ones to have finished. It then downloads all the
  # json data generated by the previous jobs before running jazzy
  run-jazzy:
    name: Run Jazzy
    needs: build-json
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - run: git fetch origin gh-pages:gh-pages
    - name: Install
      run: |
        gem install jazzy
        brew install swift-sh
    - name: Chunk 1
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-0
        path: ./sourcekitten/
    - name: Chunk 2
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-1
        path: ./sourcekitten/
    - name: Chunk 3
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-2
        path: ./sourcekitten/
    - name: Chunk 4
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-3
        path: ./sourcekitten/
    - name: Chunk 5
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-4
        path: ./sourcekitten/
    - name: Chunk 6
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-5
        path: ./sourcekitten/
    - name: Chunk 7
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-6
        path: ./sourcekitten/
    - name: Chunk 8
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-7
        path: ./sourcekitten/
    - name: Chunk 9
      uses: actions/download-artifact@v1
      with:
        name: sourcekitten-8
        path: ./sourcekitten/
    - name: Build
      run: |
        ./scripts/build-doc.sh
    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REMOTE_BRANCH: "gh-pages"
        FOLDER: "current"
      run: |
        REMOTE_REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git checkout ${REMOTE_BRANCH}
        rm -rf ${FOLDER}/
        mv docs/ ${FOLDER}/
        git add --all ${FOLDER}

        git commit -m "Documentation for https://github.com/${GITHUB_REPOSITORY}/tree/${GITHUB_SHA}" -m "Generated by gen-docs.yml"
        git push ${REMOTE_REPO} ${REMOTE_BRANCH}
