sourcekitten_sourcefile:
  - sourcekitten/AWSSDKSwiftCore.json
{%for service in services %}
  - sourcekitten/{{service}}.json
{%endfor %}

author: Yuki Takei, Joe Smith, Jonathan McAllister, Adam Fowler
author_url: https://github.com/swift-aws
github_url: https://github.com/swift-aws/aws-sdk-swift
copyright: '© Copyright (c) 2020 Yuki Takei(noppoMan), Joe Smith(Yasumoto), Jonathan McAllister(jonnymacs), Adam Fowler(adam-fowler), Fabian Fett(fabianfett)'
swift_version: 5.2
theme: scripts/jazzy/themes/apple-thin-nav/
github_file_prefix: https://github.com/swift-aws/aws-sdk-swift
documentation: documentation/*.md
hide_unlisted_documentation: true
disable_search: true

custom_categories:
  - name: User Guides
    children:
      - "AWSClient and Services"
      - "Credential Providers"
      - "Streaming Payloads"
      - "DynamoDB and Codable"
      - "S3 Multipart Upload"
      - "Using AWSSDKSwift with Vapor 4"
  - name: AWSSDKSwiftCore
    children:
      - AWSClient
      - AWSPayload
      - AWSRequest
      - AWSResponse
      - AWSErrorType
      - AWSServiceMiddleware
      - AWSLoggingMiddleware
      - CredentialProvider
      - CredentialProviderFactory
      - DeferredCredentialProvider
      - RotatingCredentialProvider
      - RetryPolicy
{% for service in services %}
  - name: {{service}}
    children:
      - {{service}}
      - {{service}}ErrorType
{%endfor %}
