name: Update AWS service files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: App Token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        brew install swift-sh
        brew install mint
        echo "$HOME/.mint/bin" >> $GITHUB_PATH
    - name: Update Models
      id: update-models
      run: |
        ./scripts/update_models.sh
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: 'Update models from api-models-aws.git}'
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: aws-update-models
        title: 'Update models from api-models-aws.git'
        body: 'Automated update of AWS service files from Smithy model files in aws-sdk-go-v2 repository'
        base: main
